	SUBROUTINE ALLOCA_VARS(IOP)
	!SUBROTINA DE ALLOCAÇÃO DE MEMÓRIA DAS VARIÁVEIS PRINCIPAIS
	USE VARS_MAIN
	use AUX_MOD !RP
	use vars_calib !RP

	IMPLICIT NONE	
	INTEGER IOP
    SAVE

	ALLOCV_CASE: SELECT CASE (IOP) !VERIFICA SE ALLOCA OU DEALLOCA
	CASE (0) ! ALLOCA
		ALLOCATE (ICODMUSK(NC)) !CODIGO QUE INDICA LINEAR OU NAO LINEAR
		ALLOCATE (BPLAN(NC)) !LARGURA DA PLANÍCIE DE INUNDAÇÃO (INCLUI O PROPRIO RIO)
		ALLOCATE (HCALHA1(NC),HCALHA2(NC)) !PROF EM QUE INICIA E EM QUE A PLANICIE ESTA TOT INUNDADA
		ALLOCATE (QMUP(NC,NTMUP),AMUP(NC,NTMUP),BMUP(NC,NTMUP),CMUP(NC,NTMUP)) !TABELA MUSKINGUN NAO LINEAR
		ALLOCATE (EVQ(NC)) !EVAPORAÇÃO DIRETA DA SUPERFÍCIE LÍQUIDA DA CÉLULA EM M3/S
		ALLOCATE (QRIOINI(NC,NUMUSK+1)) !CONDIÇÃO INCIAL DA PROPAGAÇÃO MUSKINGUM CUNGE
		ALLOCATE (QCONTORM(NC+1,25),QCONTORJ(NC+1,25)) !VAZÃO DA CONDIÇÃO DE CONTORNO DE MUSKINGUM CUNGE
		ALLOCATE (SI(NC,NU))
		ALLOCATE (XYC(NCLI,2))!COORDENADAS X E Y DOS POSTOS CLIMATOLÓGICOS
		ALLOCATE (TAMM(NCLI,12),URMM(NCLI,12),VVMM(NCLI,12))
		ALLOCATE (PAMM(NCLI,12),SOLMM(NCLI,12))
		ALLOCATE (PMB(NB)) !CHUVA MEDIA POR BACIA
		ALLOCATE (KPM(NB)) !VARIAVEL AUXILIAR
if (flagaclimed/=1)		ALLOCATE (TD(NCLI,NT),UD(NCLI,NT),VD(NCLI,NT),SOLD(NCLI,NT))
if (flagaclimed/=1)		ALLOCATE (PAD(NCLI,NT))
		ALLOCATE (QREF(NC)) !VAZAO DE REFERENCIA
		ALLOCATE (ICBOM(NC))!NUMERO DO POSTO CLIMATOLOGICO MAIS PROXIMO DA CELULA
	 	ALLOCATE (PUSO(NC,NU))!PROPORCAO DE USOS NA CELULA
	 	ALLOCATE (ACEL(NC),ACUR(NC),SRIO(NC),DECL(NC))
		ALLOCATE (X(NC),Y(NC))!COORDENADAS DO CENTRO DA CELULA
		ALLOCATE (IBAC(NC),HCEL(NC),LCEL(NC),CELJUS(NC))!BACIA,HMAX,HMIN,CELULA DE JUSANTE
	 	ALLOCATE (PM(NC)) !CHUVA MEDIA E CHUVA NO INTERVALO NA CELULA
		ALLOCATE (BRIO(NC))!LARGURA DO RIO
        ALLOCATE (HRIO(NC))                 !PROFUNDAIDE DE CALHA CHEIA DO RIO                  !FMF em 06/05/2019 - leitura do novo MINI.GTP
        ALLOCATE (RUGMAN(NC)) !Manning                                                          !FMF em 06/05/2019 - leitura do novo MINI.GTP
		ALLOCATE (IEXUT(NB)) !INDICA CELULA DO EXUTORIO DA BACIA
		ALLOCATE (CI(NB),CB(NB),CS(NB)) !PARAMETROS DA PROPAGAÇÃO NA CÉLULA
		ALLOCATE (CIOLD(NB),CSOLD(NB)) !PARAMETROS DA PROPAGAÇÃO NA CÉLULA
		ALLOCATE (PLAM(NB,NU),CAP(NB,NU),WC(NB,NU))
		ALLOCATE (WMOLD(NB,NU),BOLD(NB,NU),KBOLD(NB,NU),KIOLD(NB,NU))
		ALLOCATE (WM(NB,NU),B(NB,NU),KINS(NB,NU),KBAS(NB,NU))
		ALLOCATE (NARQ(NCLI))
		ALLOCATE (NSUBT(NC)) !NUMERO DE SUBTRECHOS DE RIO PARA MUSKINGUM CUNGE (DIFERENTE PARA CADA CÉLULA)
		ALLOCATE (DT(NC)) !INTERVALO DE TEMPO MUSKINGUM CUNGE (DIFERENTE PARA CADA CÉLULA)
		ALLOCATE (CEL(NC),TIND(NC))
		ALLOCATE (ALB(NU,12),RIAF(NU,12),Z(NU,12),RS(NU,12))
		ALLOCATE (QESP(NB))	 !VAZÃO ESPECIFICA DE BASE (M3/S/KM2)
		ALLOCATE (QB(NT),QBI(NT),QBIS(NT))!VAZÃO DE ACORDO COM ORIGEM
		ALLOCATE (DSUM(NB,NT),DINM(NB,NT),DBAM(NB,NT))!MEDIAS BACIA
		ALLOCATE (SIM(NB,NT),EM(NB,NT),WBM(NB,NT),PM2(NB,NT))!MEDIAS BACIA
		ALLOCATE (KCB(NB)) !NUMERO DE CELULAS EM CADA SUB-BACIA
		ALLOCATE (QR(NOBS,NT),QOBS(NOBS,NT))!VAZÃO CALCULADA E OBSERVADA NOS EXUTORIOS DAS BACIAS
		ALLOCATE (QLIDO(NUMSUBST,NT)) !VAZÃO QUE É LIDA PARA SUBSTITUIR CALCULADA
		ALLOCATE (QMANTEIGA(NT),QSAOROM(NT),QSAOFRA(NT),QPMCRUZ(NT),QMANGA(NT),QCARI(NT))
		ALLOCATE (QBJLAPA(NT),QGAMEL(NT),QMORP(NT))
		ALLOCATE (QRG(NUMHIDG,NT)) !HIDROGRAMAS PARA GRAVAÇÃO
		ALLOCATE (QRB(NB,NT)) !HIDROGRAMAS DAS SUB-BACIAS
		ALLOCATE (QM1(NC+1),QJ1(NC),QM2(NC+1),QJ2(NC)) !VAZOES A MONTANTE E A JUSANTE EM i
		ALLOCATE (QCEL1(NC),QCEL2(NC)) !VAZÕES ORIGINADAS NA CELULA NOS INSTANTES t E t+1 NA CÉLULA i
		ALLOCATE (QCEL1PREV(NC),QCEL2PREV(NC)) !VAZÕES ORIGINADAS NA CELULA NOS INSTANTES t E t+1 NA CÉLULA i
		ALLOCATE (PMB2(NC+1),PMI2(NC+1),PMS2(NC+1),PJB2(NC+1),PJI2(NC+1),PJS2(NC+1)) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO
		ALLOCATE (VRB(NC),VRI(NC),VRS(NC)) !VOLUMES DAS PROPORÇÕES NO TRECHO
		ALLOCATE (ET(NC,NU)) 	!EVAPOTRASPIRACAO TOTAL
		ALLOCATE (CAF(NC,NU))		!FLUXO CAPILAR ASCENDENTE
		ALLOCATE (W(NC,NU)) 	!LAMINA DE AGUA NO SOLO
		ALLOCATE (QBAS(NC),QINT(NC),QSUP(NC))		!VAZAO NA CELULA
		ALLOCATE (VBAS(NC),VINT(NC),VSUP(NC))		!VOLUME NA CELULA
		ALLOCATE (TONTEM(NC))		!TEMPERATURA NO DIA ANTERIOR
		ALLOCATE (P(NC)) !CHUVA NO INTERVALO NA CELULA
		ALLOCATE (TA(NC),UR(NC),VV(NC),SOL(NC),PA(NC))	!TEMP., UMIDADE, VENTO, INSOL., PRESSAO
		ALLOCATE (R2(NOBS),ERRV(NOBS),R2L(NOBS)) !COEF. NASH, ERRO NOS VOLUMES, COEF NASH LOGARITMOS
		ALLOCATE (WPREV(NC,NU)) 	!LAMINA DE AGUA NO SOLO NO INÍCIO DO CICLO DE PREVISÃO
		ALLOCATE (VBASPREV(NC),VINTPREV(NC),VSUPPREV(NC)) !VOLUME NA CELULA NO INÍCIO DO LOOP PREVISÃO
		ALLOCATE (TAPREV(NC)) !TEMPERATURA NO DIA DE INÍCIO DO LOOP DE PREVISÃO
		ALLOCATE (QM2PREV(NC+1),QJ2PREV(NC),QJ1PREV(NC)) !VAZOES NAS CÉLULAS NO INÍCIO DO LOOP PREVISÃO
		ALLOCATE (QPREV(NUMHIDG,190,NT)) !VAZÃO PREVISTA NOS LOCAIS DE INTERESSE COM DIF. ANTECEDENCIA
		ALLOCATE (SIPREV(NC,NU)) 	!LAMINA DE AGUA INTERCEPTAÇÃO (PREVISÃO)
		ALLOCATE (QRIOINIPREV(NC,NUMUSK+1)) !CONDIÇÃO INCIAL DA PROPAGAÇÃO MUSKINGUM CUNGE
		ALLOCATE (QCONTORMPREV(NC+1,25),QCONTORJPREV(NC+1,25)) !VAZÃO DA CONDIÇÃO DE CONTORNO DE MUSKINGUM CUNGE
		ALLOCATE (PMB2PREV(NC+1),PMI2PREV(NC+1),PMS2PREV(NC+1)) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO
		ALLOCATE (PJB2PREV(NC+1),PJI2PREV(NC+1),PJS2PREV(NC+1)) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO

		allocate (OD(NC),hdFLAG(NC)) !RP
 
		ALLOCATE (CBOLD(NB),PLAMOLD(NB,NU),CAPOLD(NB,NU),WCOLD(NB,NU)) ! RP
		allocate (sbtFLAG(nC))



		! Variáveis para calculo de indicadores de evapotranspitacao máxima:
		allocate (E0agua(nC),E0TOPO(nC),E0SUP(nC))

		allocate (E0media(nC)) !RP

		allocate (TWS(nC),DTWS(nC),QM2in(nC),QM1in(nC)) ! RP
		allocate (TWS1(nC),TWS2(nC),TWS3(nC),TWS4(nC),TWS5(nC),TWS6(nC),TWS7(nC)) ! RP



	CASE (1) ! DEALLOCA
		DEALLOCATE (ICODMUSK) !CODIGO QUE INDICA LINEAR OU NAO LINEAR
		DEALLOCATE (BPLAN) !LARGURA DA PLANÍCIE DE INUNDAÇÃO (INCLUI O PROPRIO RIO)
		DEALLOCATE (HCALHA1,HCALHA2) !PROF EM QUE INICIA E EM QUE A PLANICIE ESTA TOT INUNDADA
		DEALLOCATE (QMUP,AMUP,BMUP,CMUP) !TABELA MUSKINGUN NAO LINEAR
		DEALLOCATE (QMANTEIGA,QSAOROM,QSAOFRA,QPMCRUZ,QMANGA,QCARI)
		DEALLOCATE (QBJLAPA,QGAMEL,QMORP)
		DEALLOCATE (EVQ) !EVAPORAÇÃO DIRETA DA SUPERFÍCIE LÍQUIDA DA CÉLULA EM M3/S
		DEALLOCATE (QCONTORM,QCONTORJ) !VAZÃO DA CONDIÇÃO DE CONTORNO DE MUSKINGUM CUNGE
		DEALLOCATE (WMOLD,BOLD,KBOLD,KIOLD)
		DEALLOCATE (XYC)!COORDENADAS X E Y DOS POSTOS CLIMATOLÓGICOS
		DEALLOCATE (TAMM,URMM,VVMM)
		DEALLOCATE (PAMM,SOLMM)
		DEALLOCATE (PMB,KPM) !CHUVA MEDIA POR BACIA E VARIAVEL AUXILIAR
if (flagaclimed/=1)		DEALLOCATE (TD,UD,VD,SOLD)
if (flagaclimed/=1)		DEALLOCATE (PAD)
		DEALLOCATE (QREF) !VAZAO DE REFERENCIA
		DEALLOCATE (ICBOM)!NUMERO DO POSTO CLIMATOLOGICO MAIS PROXIMO DA CELULA
	 	DEALLOCATE (PUSO)!PROPORCAO DE USOS NA CELULA
	 	DEALLOCATE (ACEL,ACUR,SRIO,DECL)
		DEALLOCATE (X,Y)!COORDENADAS DO CENTRO DA CELULA
		DEALLOCATE (IBAC,HCEL,LCEL,CELJUS)!BACIA,HMAX,HMIN,CELULA DE JUSANTE
	 	DEALLOCATE (PM) !CHUVA MEDIA E CHUVA NO INTERVALO NA CELULA
		DEALLOCATE (BRIO)!LARGURA DO RIO
		DEALLOCATE (HRIO)                 !PROFUNDAIDE DE CALHA CHEIA DO RIO           !FMF em 06/05/2019 - leitura do novo MINI.GTP
        DEALLOCATE (RUGMAN) !Manning                                                   !FMF em 06/05/2019 - leitura do novo MINI.GTP
		DEALLOCATE (IEXUT) !INDICA CELULA DO EXUTORIO DA BACIA
		DEALLOCATE (CI,CB,CS) !PARAMETROS DA PROPAGAÇÃO NA CÉLULA
		DEALLOCATE (CIOLD,CSOLD) !PARAMETROS DA PROPAGAÇÃO NA CÉLULA
		DEALLOCATE (PLAM,CAP,WC)
		DEALLOCATE (WM,B,KINS,KBAS)
		DEALLOCATE (NARQ)
		DEALLOCATE (NSUBT,DT)
		DEALLOCATE (CEL,TIND)
		DEALLOCATE (ALB,RIAF,Z,RS)
		DEALLOCATE (QESP)	 !VAZÃO ESPECIFICA DE BASE (M3/S/KM2)
		DEALLOCATE (QB,QBI,QBIS)!VAZÃO DE ACORDO COM ORIGEM
		DEALLOCATE (DSUM,DINM,DBAM)!MEDIAS BACIA
		DEALLOCATE (SIM,EM,WBM,PM2)!MEDIAS BACIA
		DEALLOCATE (KCB) !NUMERO DE CELULAS EM CADA SUB-BACIA
		DEALLOCATE (QR,QOBS)!VAZÃO CALCULADA E OBSERVADA NOS EXUTORIOS DAS BACIAS
		DEALLOCATE (SI)
		DEALLOCATE (QRG) 	!VAZÃO NOS EXUTORIOS DAS BACIAS
		DEALLOCATE (QRB) !HIDROGRAMAS DAS SUB-BACIAS
		DEALLOCATE (QM1,QJ1,QM2,QJ2) !VAZOES A MONTANTE E A JUSANTE EM i
		DEALLOCATE (PMB2,PMI2,PMS2,PJB2,PJI2,PJS2) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO
		DEALLOCATE (VRB,VRI,VRS) !VOLUMES DAS PROPORÇÕES NO TRECHO
		DEALLOCATE (ET) 	!EVAPOTRASPIRACAO TOTAL
		DEALLOCATE (CAF)		!FLUXO CAPILAR ASCENDENTE
		DEALLOCATE (W) 	!LAMINA DE AGUA NO SOLO
		DEALLOCATE (QBAS,QINT,QSUP)		!VAZAO NA CELULA
		DEALLOCATE (VBAS,VINT,VSUP)		!VOLUME NA CELULA
		DEALLOCATE (TONTEM)		!TEMPERATURA NO DIA ANTERIOR
		DEALLOCATE (P) !CHUVA NO INTERVALO NA CELULA
		DEALLOCATE (TA,UR,VV,SOL,PA)	!TEMP., UMIDADE, VENTO, INSOL., PRESSAO
		DEALLOCATE (R2,ERRV,R2L) !COEF. NASH, ERRO NOS VOLUMES, COEF NASH LOGARITMOS
		DEALLOCATE (QCEL1,QCEL2) !VAZÕES ORIGINADAS NA CELULA NOS INSTANTES t E t+1 NA CÉLULA i
		DEALLOCATE (QLIDO) !VAZAO DE SUBSTITUIÇAO DA CALCULADA
		DEALLOCATE (PMB2PREV,PMI2PREV,PMS2PREV) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO
		DEALLOCATE (PJB2PREV,PJI2PREV,PJS2PREV) !PROPORÇÕES DE ORIGEM DAS VAZÕES NO RIO

		deallocate (OD,hdFLAG) !RP

		deallocate (TWS) !RP

	CASE DEFAULT
		STOP ' ERRO: IOP DESCONHECIDO NO ROTINA ALLOCA_CALIB!!!'
	END SELECT ALLOCV_CASE





	END