	SUBROUTINE ALLOCA_CALIB(IOP)
	USE VARS_CALIB
	IMPLICIT NONE
	INTEGER IOP
    SAVE

	ALLOC_CASE: SELECT CASE (IOP) !VERIFICA SE ALLOCA OU DEALLOCA
	CASE (0) ! ALLOCA
		ALLOCATE (IRUIM(NS))
		ALLOCATE (FO(NS,NF)) !FUNÇÕES OBJETIVO
		ALLOCATE (IPARET(NS))
		ALLOCATE (XPAR(NPAR))
		ALLOCATE (SOMAPAR(NPAR),REFLEX(NPAR),CONTRA(NPAR)) !SOMA DAS COORD., PONTO DE REFLEXÃO, PONTO DE CONTRAÇÃO
		ALLOCATE (MEDIA(NS)) !MÉDIA DE FUNÇÕES OBJETIVO DA POPULAÇÃO
		ALLOCATE (PPAR(NPAR,NS)) !VALOR RELATIVO DO PARAMETRO NA FAIXA DE VALIDADE
		ALLOCATE (PAR(NPAR,NS)) !VALOR DO PARAMETRO 
!		ALLOCATE (PMIN(NPAR),PMAX(NPAR)) !FAIXA DE VALIDADE DOS PARAMETROS
		ALLOCATE (FOLD(NS)) !ANTIGO VALOR DA FUNÇÃO EM CADA PONTO DA AMOSTRA
		ALLOCATE (PROB(NS)) !PROBAB. DE ESCOLHA PONTO 1..NS
		ALLOCATE (VMIN(NF)) !VALOR MINIMO DAS FUNÇÕES OBJETIVO
		ALLOCATE (PARX(NPAR)) !VALOR DO PARAMETRO 
!		
	CASE (1) ! DEALLOCA
		DEALLOCATE (IRUIM,FO,IPARET,XPAR)
		DEALLOCATE (SOMAPAR,REFLEX,CONTRA) !SOMA DAS COORD., PONTO DE REFLEXÃO, PONTO DE CONTRAÇÃO
		DEALLOCATE (MEDIA) !MÉDIA DE FUNÇÕES OBJETIVO DA POPULAÇÃO
		DEALLOCATE (PPAR) !VALOR RELATIVO DO PARAMETRO NA FAIXA DE VALIDADE
		DEALLOCATE (PAR) !VALOR DO PARAMETRO 
		DEALLOCATE (PMIN,PMAX) !FAIXA DE VALIDADE DOS PARAMETROS
		DEALLOCATE (FOLD) !ANTIGO VALOR DA FUNÇÃO EM CADA PONTO DA AMOSTRA
		DEALLOCATE (PROB) !PROBAB. DE ESCOLHA PONTO 1..NS
		DEALLOCATE (VMIN) !VALOR MINIMO DAS FUNÇÕES OBJETIVO
	CASE DEFAULT
		STOP ' ERRO: IOP DESCONHECIDO NO ROTINA ALLOCA_CALIB!!!'
	END SELECT ALLOC_CASE

	!ESTA SUBROTINA TEM OS COMANDOS DE ALLOCAÇÃO DE MEMÓRIA DAS VARIÁVEIS DA CALIBRAÇÃO AUTOMÁTICA

	RETURN
	END