	SUBROUTINE ATUALIZA
	!Esta sub-rotina é utilizada pela sub-rotina previsão para fazer a atualização
	!de algumas variáveis no instante T0, em que inicia o ciclo de previsão. 
	!A base para a atualização é a comparação com algum dado observado de vazão.
	USE VARS_MAIN
	USE AUX_MOD
	IMPLICIT NONE
	REAL PESOBAC
	INTEGER ITR1,NTRECH,NTMUSK,LT,I,J,K

	REAL EXPOENTEBAC(NB) !INDICA O EXPOENTE PARA PONDERAR A ÁREA DA BACIA
	REAL EXPOBAS(NB) !INDICA O EXPOENTE PARA CORRIGIR ARMAZENAMENTO SUBTERRANEO: 1 = RÁPIDO 0.1 = LENTO
	REAL EXPOINT(NB) !INDICA O EXPOENTE PARA CORRIGIR ARMAZENAMENTO SUBSUPERFICIAL: 1 = RÁPIDO 0.1 = LENTO
	REAL EXPOSUP(NB) !INDICA O EXPOENTE PARA CORRIGIR ARMAZENAMENTO SUPERFICIAL: 1 = RÁPIDO 0.1 = LENTO
	REAL PLIMBAS(NB) !PROPORÇaO LIMITE PARA CORRIGIR ARM SUBTERRANEO
	REAL PLIMINT(NB) !PROPORÇaO LIMITE PARA CORRIGIR ARM SUB-SUPERFICIAL
	REAL PLIMSUP(NB) !PROPORÇaO LIMITE PARA CORRIGIR ARM SUPERFICIAL
	INTEGER NDIASFSUP(NB),NDIASFINT(NB),NDIASFBAS(NB) !NUMERO DE DIAS PARA FAZER A ESTIMATIVA DO ERRO 
	REAL SOMACAL,SOMAOBS
	REAL FCORSUP(NB),FCORINT(NB),FCORBAS(NB) !FATORES DE CORREÇÃO PARA CADA BACIA E PARA CADA PARTE DA VAZAO OU ARM
	INTEGER IWW





	!INDICA O EXPOENTE UTILIZADO PARA PONDERAR ÁREA DA BACIA
	EXPOENTEBAC=1.0

	!INDICA O EXPOENTE UTILIZADO PARA CORREÇÃO DE ÁGUA SUBTERRÂNEA
	!VALOR = 1 CORRIGE MUITO RAPIDAMENTE
	!VALOR PRÓXIMO DE ZERO (0.1) CORRIGE LENTAMENTE
	EXPOBAS=0.2

	!CONSIDERA QUE O EXPOENTE PARA CORREÇÃO DE ÁGUA SUPERFICIAL E SUB-SUPERFICIAL É IGUAL A EXPOBAS
	EXPOINT=EXPOBAS
	EXPOSUP=EXPOBAS
	!INDICA A PROPORÇÃO DE ÁGUA SUBTERRÂNEA NA VAZÃO TOTAL PARA COMEÇAR A CORRIGIR ARMAZENAMENTO SUBTERRÂNEO
	PLIMBAS=0.6
	!INDICA A PROPORÇÃO DE ÁGUA SUB-SUPERFICIAL NA VAZAO TOTAL PARA COMEÇAR A CORRIGIR ARMAZENAMENTO
	PLIMINT=0.6

	!INDICA A PROPORÇÃO DE ÁGUA SUPERFICIAL NA VAZÃO TOTAL PARA COMEÇAR A CORRIGIR ARMAZENAMENTO
	PLIMSUP=0.6
	!INDICA O NÚMERO DE DIAS PARA FAZER A MÉDIA E CALCULAR O ERRO E O FATOR DE CORREÇÀO
	NDIASFINT=1
	NDIASFSUP=1
	NDIASFBAS=7 !PARA TODOS COMEÇA COM 7, VAI MODIFICAR DEPOIS

	NTMUSK=DTP/DT(NC) !CONSIDERA QUE O NUMERO DE INTERVALOS DE TEMPO MUSK CUNGE É IGUAL EM TODAS AS CELULAS

	FCORBAS=1.0
	FCORSUP=1.0
	FCORINT=1.0

	DO I=1,NB

		!CALCULA FATOR PARA CORREÇÃO DA VAZÃO SUPERFICIAL 
		J=POSTOSUP(I)

		if (J>0) then
		
			SOMACAL=0.0
			SOMAOBS=0.0
			DO IWW=1,NDIASFSUP(I) !USA O NUMERO DE DIAS INDICADO
				IF(QOBS(J,IT+1-IWW)>0.0)THEN
					SOMAOBS=SOMAOBS+QOBS(J,IT+1-IWW)
					SOMACAL=SOMACAL+QR(J,IT+1-IWW)
				ENDIF
			ENDDO
			IF(SOMACAL>0.0)THEN
				FCORSUP(I)=SOMAOBS/SOMACAL
			ELSE
				FCORSUP(I)=1.0
			ENDIF
		endif
		!CALCULA FATOR PARA CORREÇÃO DA VAZÃO SUB-SUPERFICIAL
		J=POSTOINT(I)
		if (J>0) then
			SOMACAL=0.0
			SOMAOBS=0.0
			DO IWW=1,NDIASFINT(I) !USA O NUMERO DE DIAS INDICADO
				IF(QOBS(J,IT+1-IWW)>0.0)THEN
					SOMAOBS=SOMAOBS+QOBS(J,IT+1-IWW)
					SOMACAL=SOMACAL+QR(J,IT+1-IWW)
				ENDIF
			ENDDO
			IF(SOMACAL>0.0)THEN
				FCORINT(I)=SOMAOBS/SOMACAL
			ELSE
				FCORINT(I)=1.0
			ENDIF
		endif

		!CALCULA FATOR PARA CORREÇÃO DA VAZÃO SUBTERRÂNEA
		J=POSTOBAS(I)
		if (J>0) then
			SOMACAL=0.0
			SOMAOBS=0.0
			DO IWW=1,NDIASFBAS(I) !USA O NUMERO DE DIAS INDICADO
				IF(QOBS(J,IT+1-IWW)>0.0)THEN
					SOMAOBS=SOMAOBS+QOBS(J,IT+1-IWW)
					SOMACAL=SOMACAL+QR(J,IT+1-IWW)
				ENDIF
			ENDDO
			IF(SOMACAL>0.0)THEN
				FCORBAS(I)=SOMAOBS/SOMACAL
			ELSE
				FCORBAS(I)=1.0
			ENDIF
		endif

		!LIMITA O VALOR MÁXIMO E O MÍNIMO DA CORRECAO PARA NAO EXAGERAR NA CORRECAO
		FCORBAS(I)=MIN(FCORBAS(I),2.0)
		FCORBAS(I)=MAX(FCORBAS(I),0.2)
		FCORSUP(I)=MIN(FCORSUP(I),2.0)
		FCORSUP(I)=MAX(FCORSUP(I),0.5)
		FCORINT(I)=MIN(FCORINT(I),2.0)
		FCORINT(I)=MAX(FCORINT(I),0.5)

	ENDDO

	if (1==1) then
	DO IC=1,NC
		IF (hdFLAG(IC)==1) CYCLE ! Nao atualiza onde tem modelo hidrodinamico
		
		NTRECH=NSUBT(IC)
		I=IBAC(IC)
		K=POSTORIO(I)


		!CORRIGE ÁGUA SUBTERRÂNEA
		IF(POSTOBAS(I)>0.AND.PJB2(IC)>PLIMBAS(I))THEN
			!WRITE(*,*)IT,I,IC,VBAS(IC)

			!VBAS(IC)=VBAS(IC)*(FCORBAS(POSTOBAS(I))**EXPOBAS(I))*PJB2(IC)+VBAS(IC)*(1.-PJB2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VBAS(IC)=VBAS(IC)*(FCORBAS(I)**EXPOBAS(I))*PJB2(IC)+VBAS(IC)*(1.-PJB2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			!VBASPREV(IC)=VBASPREV(IC)*(FCORBAS(POSTOBAS(I))**EXPOBAS(I))*PJB2(IC)+VBASPREV(IC)*(1.-PJB2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VBASPREV(IC)=VBASPREV(IC)*(FCORBAS(I)**EXPOBAS(I))*PJB2(IC)+VBASPREV(IC)*(1.-PJB2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
		ENDIF
		!CORRIGE ÁGUA SUB-SUPERFICIAL
		IF(POSTOINT(I)>0.AND.PJI2(IC)>PLIMINT(I))THEN
			!VINT(IC)=VINT(IC)*(FCORINT(POSTOINT(I))**EXPOINT(I))*PJI2(IC)+VINT(IC)*(1.-PJI2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			!VINTPREV(IC)=VINTPREV(IC)*(FCORINT(POSTOINT(I))**EXPOINT(I))*PJI2(IC)+VINTPREV(IC)*(1.-PJI2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VINT(IC)=VINT(IC)*(FCORINT(I)**EXPOINT(I))*PJI2(IC)+VINT(IC)*(1.-PJI2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VINTPREV(IC)=VINTPREV(IC)*(FCORINT(I)**EXPOINT(I))*PJI2(IC)+VINTPREV(IC)*(1.-PJI2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
		ENDIF

		!CORRIGE ÁGUA SUPERFICIAL
		IF(POSTOSUP(I)>0.AND.PJS2(IC)>PLIMSUP(I))THEN
			!VSUP(IC)=VSUP(IC)*(FCORSUP(POSTOSUP(I))**EXPOSUP(I))*PJS2(IC)+VSUP(IC)*(1.-PJS2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			!VSUPPREV(IC)=VSUPPREV(IC)*(FCORSUP(POSTOSUP(I))**EXPOSUP(I))*PJS2(IC)+VSUPPREV(IC)*(1.-PJS2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VSUP(IC)=VSUP(IC)*(FCORSUP(I)**EXPOSUP(I))*PJS2(IC)+VSUP(IC)*(1.-PJS2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
			VSUPPREV(IC)=VSUPPREV(IC)*(FCORSUP(I)**EXPOSUP(I))*PJS2(IC)+VSUPPREV(IC)*(1.-PJS2(IC)) !CORRIGE VOLUME NO RESERVATÓRIO SUBTERRÂNEO
		ENDIF

		VSUP(IC)=MAX(VSUP(IC),0.0)
		VINT(IC)=MAX(VINT(IC),0.0)
		VBAS(IC)=MAX(VBAS(IC),0.0)



		IF(POSTORIO(I)>0)THEN
			K=IQOBS(K)
			PESOBAC=(ACUR(IC)/ACUR(K))**EXPOENTEBAC(I) !PONDERADOR PARA CORREÇÀO NAS OUTRAS CÉLULAS
			!QJ2PREV(IC)=(QJ2(IC)*FCORSUP(POSTORIO(I)))*PESOBAC+QJ2(IC)*(1.-PESOBAC)
			QJ2PREV(IC)=(QJ2(IC)*FCORSUP(I))*PESOBAC+QJ2(IC)*(1.-PESOBAC)
			QJ2(IC)=QJ2PREV(IC)
			DO ITR1=1,NTRECH+1 !ATUALIZA CONDIÇOES INICIAIS DE MUSKINGUM CUNGE 
				!QRIOINI(IC,ITR1)=QRIOINI(IC,ITR1)*FCORSUP(POSTORIO(I))*PESOBAC+QRIOINI(IC,ITR1)*(1.-PESOBAC)
				QRIOINI(IC,ITR1)=QRIOINI(IC,ITR1)*FCORSUP(I)*PESOBAC+QRIOINI(IC,ITR1)*(1.-PESOBAC)
				QRIOINIPREV(IC,ITR1)=QRIOINI(IC,ITR1)
			ENDDO
			DO LT=1,NTMUSK+1
				!QCONTORM(IC,LT)=(QCONTORM(IC,LT)*FCORSUP(POSTORIO(I)))*PESOBAC+QCONTORM(IC,LT)*(1.-PESOBAC)
				QCONTORM(IC,LT)=(QCONTORM(IC,LT)*FCORSUP(I))*PESOBAC+QCONTORM(IC,LT)*(1.-PESOBAC)
				QCONTORMPREV(IC,LT)=QCONTORM(IC,LT)
			ENDDO
		ENDIF
	ENDDO
	endif

	RETURN
	END
