	SUBROUTINE EVAPO

	!ESTA SUBROTINA CALCULA A EVAPOTRANSPIRAÇÃO
	!MSF$DEBUG
	USE VARS_MAIN
	IMPLICIT NONE


	!	REAL WX,WMX,PAX,TAX,VVX,RIAFX,DTP
	!REAL RLX !RADIAÇÃO LIQUIDA (MJ/m2/dia)
	!REAL CLATE !calor latente de vaporização
	!REAL ED,ES !PRESSÕES DE VAPOR (REAL, SATURAÇAO)
	!REAL D !DEFICIT DE PRESSAO DE VAPOR
	!REAL DEL !DERIVADA DA FUNÇAO ES x T
	!REAL GAMA !CONSTANTE PSICROMÉTRICA
	!REAL MSPA !MASSA ESPECÍFICA DO AR
	!REAL ZX,RSX !ALTURA E RESISTÊNCIA SUPERFICIAL DA VEG.
	!REAL RUG !RUGOSIDADE
	!REAL SIX !LAMINA INTERCEPTADA 
	!REAL SF !IDEM
	!REAL SIL !MAXIMA LAMINA INTERCEPTADA
	!REAL EIX !LAMINA EVAPORADA DA INTERCEPTAÇÃO (POTENCIAL)
	!REAL REIX !LAMINA EVAPORADA DA INTERCEPTAÇÃO (REAL)
	!REAL FDE !FRAÇÃO DE DEMANDA EVAPORATIVA DISPONIVEL
	!REAL PX !PRECIPITAÇÃO
	!REAL,PARAMETER:: MESP=1000.0 !MASSA ESP. DA ÁGUA (KG/M3)
	!REAL,PARAMETER:: CSPA=0.001013 	!calor esp. do ar umido MJ/kg/C
	!REAL RA !RESISTÊNCIA AERODINÂMICA
	!REAL WL !LIMITE DE UMIDADE ACIMA DO QUAL A UMIDADE DO SOLO NAO RESTRINGE A EVAPOTRANSPIRAÇAO (SHUTTLEWORTH)
	!REAL WPM !PONTO DE MURCHA (SHUTTLEWORTH)
	!REAL F4 !FATOR DE CORREÇÃO DA RESISTÊCNIA SUPERFICIAL EM FUNÇÃO DO DEFICIT DE UMIDADE DO SOLO
	!REAL EX !EVAPORAÇÃO ATRAVÉS DO SOLO+PLANTA
	!REAL ETX !EVAPOTRASNPIRAÇÃO TOTAL REAL (ÁGUA INTERCEPTADA + SOLO + PLANTA)

	D=ES-ED !DEFICIT EM KPA
	GAMA=0.0016286*PAX/CLATE ! EM KPA/C (EQ. 4.2.28)
	DEL=(4098.0*ES)/((237.3+TAX)**2.) ! (EQ. 4.2.3)
	MSPA=3.486*(PAX/(275.0+TAX)) !EM KG/M3 (EQ. 4.2.4)

	RLX=RLX/(3600.0*24.0) !RLX EM MJ/m2/s

	!RUGOSIDADE AERODINAMICA DA SUPERFÍCIE VEGETAL 
	RUG=0.1*ZX


	!A PARTE DE RESISTÊNCIA AERODINAMICA FOI OBTIDA DO
	!TRABALHO DE Bremicker
	
	!CORRIGE MEDIDA DE VELOCIDADE DE 2 M PARA 10 M DO CHAO
	IF (flagaclimed == 1) then
		! Seu utiliza dados CRU o vento ja esta em 10 m.
		VVX=VVX
	else
		VVX=VVX*((LOG(10.0/RUG))/LOG(2.0/RUG)) !EQ. 3.46
	endif	

	VVX=VVX+0.1 !EVITA PROBLEMAS COM VALOR ZERO



	!RESISTÊNCIA AERODINAMICA SEGUNDO ESQUEMA DO LARSIM
	!IF(ZX.LT.10.0) THEN
	!	RA=(6.25/VVX)*(LOG(10.0/RUG))**2.0 !EQ. 3.25
	!ELSE
	!	RA=94.0/VVX !EQ. 3.26
	!
	!ENDIF


	!MODIFICAÇÃO 2010 RESISTENCIA AERODINAMICA SEGUNDO SHUTTLEWORTH
	ZX=MIN(ZX,12.5) !LIMITA ALTURA DA VEGETAÇÃO PARA NÃO TER PROBLEMAS NA EQUAÇÃO DO SHUTTLEWORTH
	RA=((LOG((10.-ZX*0.67)/(ZX*0.123)))*(LOG((10.-ZX*0.67)/(ZX*0.0123))))/(0.41*0.41*VVX)

	!CALCULA A RESISTÊNCIA SUPERFICIAL (RSX) EM CONDIÇÕES QUAISQUER DE UMIDADE DO SOLO
	WL=0.5*WMX !LIMITE DE UMIDADE ACIMA DO QUAL A UMIDADE DO SOLO NAO RESTRINGE A EVAPOTRANSPIRAÇAO (SHUTTLEWORTH)
	WPM=0.1*WMX !PONTO DE MURCHA (SHUTTLEWORTH)
	!RSX=RSX !RS É LIDO DO ARQUIVO ALBIAF.HIG

	!VARIAÇÃO DA RESISTÊNCIA SUPERIFICIAL COM A UMIDADE DO SOLO (Wigmosta et al. 1994 - equação 16)
	IF(WMX<0.1)THEN !ÁGUA NÃO TEM RESISTêNCIA SUPERFICIAL
		RSX=0.0
	ELSE
		IF(WX.LE.WPM) THEN
			RSX=999999999.0 !SOLO SECO, RESISTÊNCIA SUPERFICIAL MUITO ALTA
		ELSEIF(WX.LT.WL)THEN
			F4=(WX-WPM)/(WL-WPM)
			F4=1./F4	!DEFICIT DE UMIDADE
		ELSE
			F4=1.0
		ENDIF
		RSX=F4*RSX	!SE F4>1 AUMENTA RESISTÊNCIA SUPERFICIAL
	ENDIF

	!CALCULA A EVAPORAÇÃO DA ÁGUA INTERCEPTADA
	!DEFINE A MAXIMA INTERCEPTAÇÃO
	SIL=0.2*RIAFX !*(DTP/86400.)	!SIL=0.2*RIAFX !CONFORME Wigmosta et al. 1994 e tambem usado por Bremicker

	!INCORPORA A CHUVA À LAMINA QUE PODE SER EVAPORADA
	SF=MIN(SIX+PX,SIL)
	!CORRIGE A CHUVA

	PX=PX-(SF-SIX)

	!EVAPORAÇÃO POTENCIAL DA ÁGUA INTERCEPTADA (REPARE QUE RSX=0.0)
	!EIX=((DEL*RLX+MSPA*CSPA*D/RA)/(DEL+GAMA*(1.0+0.0/RA)))*((1000.0*3600.0*24.)/(CLATE*MESP)) !mm/dia
	EIX=((DEL*RLX+MSPA*CSPA*D/RA)/(DEL+GAMA*(1.0+0.0/RA)))*((1000.0*DTP)/(CLATE*MESP)) !mm/dtp

	!EVAPORAÇÃO REAL NÃO PODE SER MAIOR DO QUE A LAMINA INTERCEPTADA
	REIX=MIN(EIX,SF) !REIX=EVAPORAÇÃO DA ÁGUA INTERCEPTADA
	!RETIRA EVAPORAÇÃO DO RESERVATÓRIO DE INTERCEPTAÇÃO

	SIX=SF-REIX	 
	!CALCULA FRAÇÃO DE DEMANDA EVAPORATIVA QUE SOBRA APOS A EVAPORAÇÃO DO VOLUME INTERCEPTADO
	FDE=(EIX-REIX)/EIX

	!CALCULA PENMANN DIRETO EM MM/DIA
	!EX=((DEL*RLX+MSPA*CSPA*D/RA)/(DEL+GAMA*(1.0+RSX/RA)))*((1000.0*3600.0*24.)/(CLATE*MESP)) !mm/dia

	EX=((DEL*RLX+MSPA*CSPA*D/RA)/(DEL+GAMA*(1.0+RSX/RA)))*((1000.0*DTP)/(CLATE*MESP)) !mm/dtp
	EX=FDE*EX  !EX=EVAPORAÇÃO ATRAVÉS DO SOLO+PLANTA
	ETX=EX+REIX !EVAPORAÇÃO TOTAL (INTERCEPT. + SOLO) 

	EX=EX*1.0

    !IF(IU==1)THEN
    !    WRITE(*,*)EX,EIX
    !ENDIF

	RETURN
	END