	SUBROUTINE FOBJ
	!ESTA SUBROTINA ANALISA A QUALIDADE DO AJUSTE ENTRE OS HIDROGRAMAS CALCULADOS E OBSERVADOS
	!COM BASE EM ALGUMAS FUNÇÕES OBJETIVO
	USE VARS_MAIN
	use vars_calib !RP
	IMPLICIT NONE
	INTEGER NANO,KB
	REAL SR,ERRVT,SRL

	REAL POND(NOBS,3)

!	REAL POND(NOBS,nf)

	INTEGER INIAJU !DIA DO INICIO DA COMPARAÇÃO CALCULADO X OBSERVADO
	REAL SOMAOBS !SOMATORIO DOS VALORES DE VAZÃO OBSERVADOS
	REAL SOMACAL !SOMATORIO DOS VALORES DE VAZÃO CALCULADOS
	REAL SOMALOGS !SOMATORIO DOS VALORES DOS LOGARITMOS DE VAZÃO OBSERVADOS
	REAL SOMALCAL !SOMATORIO DOS VALORES DOS LOGARITMOS DE VAZÃO CALCULADOS
	INTEGER ITVAL !CONTA O NUMERO DE DIAS EM QUE EXISTE VAZÃO OBSERVADA PARA COMPARAR
	REAL XMOBS,XLOGS !VAZÃO MÉDIA OBSERVADA, MÉDIA DOS LOGARITMOS DAS VAZÕES OBSERVADAS
	REAL SQDES(NOBS) !SOMATORIO DOS DESVIOS QUADRADOS ENTRE A VAZÃO OBSERVADA E CALCULADA
	REAL SOMQ !SOMATORIO DOS DESVIOS QUADRADOS ENTRE A VAZÃO OBSERVADA E A MÉDIA
	REAL SQLOG !IGUAL AO SQDES SÓ QUE PARA OS LOGARITMOS DAS VAZÕES
	REAL SOLOG !IGUAL AO SOMQ SÓ QUE PARA OS LOGARITMOS DAS VAZÕES
	integer i,j

	!QR(NOBS,NT),QOBS(NOBS,NT) !VAZÃO NOS EXUTORIOS DAS BACIAS: CALCULADA, OBSERVADA
	! NOBS,IQOBS(NOBS) !NUMERO DE SERIES DE VAZAO OBSERVADA

	!INIAJU=5300 !INDICA O DIA EM QUE INICIA A COMPARAÇÃO COM OBSERVADOS
!	iniaju=9000
    iniaju=360
	SQDES=0.0
	R2=-100.0
	R2L=-100.0
	ERRV=1000.0

	DO KB=1,NOBS
		IB=KB


		SOMAOBS=0.0
		SOMACAL=0.0
		SOMALOGS=0.0
		SOMALCAL=0.0
		SOMQ=0.0
		SQLOG=0.0
		SOLOG=0.0
		ITVAL=0
		IF(INIAJU.LT.NT)THEN
			DO IT=INIAJU,NT
				!WRITE(*,*)IB,IT,QOBS(IB,IT),QR(IB,IT)
				IF(QOBS(IB,IT).GE.0.0) THEN
					SOMAOBS=SOMAOBS+QOBS(IB,IT)
					SOMACAL=SOMACAL+QR(IB,IT)
					SOMALOGS=SOMALOGS+LOG(QOBS(IB,IT)+0.0001) !SOMA UM VALOR MUITO PEQUENO PARA EVITAR LOGARITMO DE ZERO					
                    SOMALCAL=SOMALCAL+LOG(QR(IB,IT)+0.0001)
					ITVAL=ITVAL+1
				ENDIF
			ENDDO
            
			XMOBS=SOMAOBS/ITVAL
			XLOGS=SOMALOGS/ITVAL
			IMES=0
			NANO=0
			DO IT=INIAJU,NT
				!WRITE(*,*)IB,IT,QOBS(IB,IT),QR(IB,IT)
				IF(QOBS(IB,IT).GE.0.0) THEN
					SQDES(IB)=SQDES(IB)+(QOBS(IB,IT)-QR(IB,IT))**2.0
					SOMQ=SOMQ+(QOBS(IB,IT)-XMOBS)**2.0
					SQLOG=SQLOG+(LOG(QOBS(IB,IT)+0.0001)-LOG(QR(IB,IT)+0.0001))**2.0
					SOLOG=SOLOG+(LOG(QOBS(IB,IT)+0.0001)-XLOGS)**2.0
				ENDIF
			ENDDO
			
			if (ITVAL>0) then
				R2(IB)=1.-SQDES(IB)/SOMQ
				R2L(IB)=1.-SQLOG/SOLOG
				ERRV(IB)=(SOMACAL/SOMAOBS-1.0)*100.
			endif
		ENDIF
	ENDDO



	
	SR=0.0
	SRL=0.0
	ERRVT=0.0




	! Considera funcao objetivo média ponderada dos postos que entram na calibracao
	if (icalib==0) then
		calibFLAG=1.0
	endif
	
	POND=0.0
	do kb=1,nobs
		do j=1,nf
			if (calibFLAG(kb,j)>0.0) POND(kb,j)=calibFLAG(kb,j)/sum(calibFLAG(:,j))
		enddo
	enddo
	
	VFO=0.0
	do kb=1,nobs
!	write(*,*) kb,VFO(1)
!	write(*,*) R2(kb)
!	write(*,*) POND(kb,1)
		if (POND(kb,1)>0.0) VFO(1)=VFO(1)+(1.-R2(kb))*POND(kb,1)
		if (POND(kb,2)>0.0) VFO(2)=VFO(2)+(1.-R2L(kb))*POND(kb,2)
		if (POND(kb,3)>0.0) VFO(3)=VFO(3)+ABS(ERRV(kb))*POND(kb,3)
	enddo
	

!	WRITE(*,*)(R2(IB),IB=1,NOBS)
!	WRITE(*,*)(R2L(IB),IB=1,NOBS)
!	WRITE(*,*)(ERRV(IB),IB=1,NOBS)


	write(*,*) VFO(1),VFO(2),VFO(3)


	RETURN
	END