	SUBROUTINE funcd(DX,F,DF,QREF,B,SO,CEL,DTCAL)
	!CALCULA O VALOR DE UMA FUNÇÃO PARA A SUB-ROTINA NEWTON RAPHSON
	IMPLICIT NONE
	REAL DX,F,DF
	REAL QREF,B,SO,CEL,DTCAL

	F=QREF/(B*SO*CEL)+0.8*((CEL*DTCAL)**0.8)*DX**0.2-DX
	DF=0.8*((CEL*DTCAL)**0.8)*0.2*DX**(-0.8)-1.0


	RETURN
	END