	MODULE SPAMAT
	!
	!ESTE MÓDULO SERVE PARA A DECLARAÇÃO DE VARIÁVEIS
	!DIRETAMENTE RELACIONADAS À SOLUÇÃO DO SISTEMA DE EQUAÇOES
	!PELO MÉTODO DE GRADIENTES CONJUGADOS
	!
	IMPLICIT NONE
	SAVE
	INTEGER,PARAMETER:: NAOZEROMAX=30000 !NUMERO MÁXIMO DE ELEMENTOS NÃO ZERO NA MATRIZ
	!DOUBLE PRECISION SA(NAOZEROMAX) !VETOR QUE ARMAZENA OS ELEMENTOS NÃO ZERO DA MATRIZ ESPARSA
	!REAL SA(NAOZEROMAX) !VETOR QUE ARMAZENA OS ELEMENTOS NÃO ZERO DA MATRIZ ESPARSA
	REAL(8),ALLOCATABLE:: SA(:) !VETOR QUE ARMAZENA OS ELEMENTOS NÃO ZERO DA MATRIZ ESPARSA
	INTEGER,ALLOCATABLE:: IJA(:),IJA2(:) !IJA(NAOZEROMAX) !VETOR QUE ARMAZENA A POSIÇÃO DOS ELEMENTOS EM SA(NMAX)
	REAL(8),ALLOCATABLE:: bbb(:),xxi(:)

	INTEGER dimSA
	END MODULE SPAMAT