	SUBROUTINE INTECLIM
	!descobre o número do melhor posto climático para cada célula
	USE VARS_MAIN
	IMPLICIT NONE

	REAL DMIN,DIST
	INTEGER IP,IPMIN

	DO IC=1,NC !LOOP DAS CELULAS
		DMIN=1000000.0
		DO IP=1,NCLI !LOOP DOS POSTOS METEOROLOGICOS
			DIST=((X(IC)-XYC(IP,1))**2.+(Y(IC)-XYC(IP,2))**2.)**0.5
			IF(DIST.LT.DMIN)THEN !GUARDA NUMERO DO MELHOR POSTO
				DMIN=DIST
				IPMIN=IP
			ENDIF
		ENDDO
		ICBOM(IC)=IPMIN
	ENDDO
	RETURN
	END