	SUBROUTINE LECLIMA
	!esta subrotina prepara os dados climatologicos
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER KLI,MM,IYYY,ID

	!	VERIFICA EM QUE MES ESTAMOS
	CALL caldat(JDIA,MM,id,iyyy)

	DO IC=1,NC
		KLI=ICBOM(IC)
        IF(flagaclimed==1) THEN
            TA(IC)=TAMM(KLI,MM)
            UR(IC)=URMM(KLI,MM)
            VV(IC)=VVMM(KLI,MM)
            SOL(IC)=SOLMM(KLI,MM)
            PA(IC)=PAMM(KLI,MM)
            cycle
        ENDIF

		!TEMPERATURA DO AR
		IF(flagaclimed==1.or.TD(KLI,IT).LT.-200.0)THEN !TESTA FALHA (FALHA=-300.0)
			TA(IC)=TAMM(KLI,MM)	!USA MEDIA MENSAL DO POSTO
		ELSE
			TA(IC)=TD(KLI,IT) !USA DADO REAL
		ENDIF
		
		!UMIDADE RELATIVA
		IF(UD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN !TESTA FALHA (FALHA=-1.0)
			UR(IC)=URMM(KLI,MM)	!USA MEDIA MENSAL DO POSTO
		ELSE
			UR(IC)=UD(KLI,IT) !USA DADO REAL
		ENDIF

		!VELOCIDADE DO VENTO
		IF(VD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN !TESTA FALHA (FALHA=-1.0)
			VV(IC)=VVMM(KLI,MM) ! EM M/S
		ELSE
			VV(IC)=VD(KLI,IT) !USA DADO REAL
		ENDIF	        

		!HORAS DE SOL									
		IF(SOLD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN
			SOL(IC)=SOLMM(KLI,MM) !EM HORAS/DIA
		ELSE
			SOL(IC)=SOLD(KLI,IT) !USA DADO REAL
		ENDIF

		!PRESSAO ATMOSFERICA 
		IF(PAD(KLI,IT).LT.0.0.OR.flagaclimed==1)THEN
			PA(IC)=PAMM(KLI,MM) 
		ELSE
			PA(IC)=PAD(KLI,IT) !USA DADO REAL
		ENDIF
	ENDDO

734	FORMAT(5F10.2)
	RETURN
	END