	SUBROUTINE LEOUTROSQ
	!SUBROTINA QUE LÊ DADOS DE VAZÃO OBSERVADA AO LONGO DO RIO SAO FRANCISCO
	USE VARS_MAIN
	IMPLICIT NONE

	OPEN(FILOUTROS,FILE='QEIXO.PRN',STATUS='OLD')
	READ(FILOUTROS,701)CABE(1)
	DO IT=1,NT
		READ(FILOUTROS,702)CABE(1),QMANTEIGA(IT),QSAOROM(IT),QSAOFRA(IT),QPMCRUZ(IT),QMANGA(IT),QCARI(IT),QBJLAPA(IT),QGAMEL(IT),QMORP(IT)
	ENDDO
	CLOSE (FILOUTROS)
701	FORMAT(20A10)
702	FORMAT(A20,20F10.2)
	

	RETURN
	END