	SUBROUTINE LESUBST
	!SUBROTINA QUE LÊ DADOS DE VAZÃO PARA SUBSTITUIR VAZÃO CALCULADA
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER I,J,K,L

	OPEN(FILSUBS,FILE='.\input\'//ARQSUBST,STATUS='OLD')
	READ(FILSUBS,701)(CABE(K),K=1,NUMSUBST)
	DO IT=1,NT
!		READ(FILSUBS,702)CABE(1),(QLIDO(K,IT),K=1,NUMSUBST)
		READ(FILSUBS,*)I,J,L,(QLIDO(K,IT),K=1,NUMSUBST)

	ENDDO
	CLOSE (FILSUBS)
701	FORMAT(20A10)
702	FORMAT(A20,20F10.2)
	!FIM DA LEITURA DE DADOS DE VAZAO DE SUBSTITUIÇAO DE VALORES CALCULADOS


	RETURN
	END