	SUBROUTINE LEUSO
	!esta subrotina le o arquivo PARUSO.hig
	!onde estao os parametros associados ao uso 
	!como a capacidade de armazenamento do solo WM 
	!e outros
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER KB,K !,IU

	!PARAMETROS RELACIONADOS AO USO: WM(NB,NU),B(NB,NU),KINT(NB,NU),KBAS(NB,NU),PLAM(NB,NU),CAP(NB,NU),WC(NB,NU)
	REAL AUX(NB,NU),CAUX(NB)
	!	REAL WMAUX,BAUX,KINAUX,KBAUX,PLAUX,CAPAUX,WCAUX
	!PARAMETROS DA PROPAGAÇÃO NA CÉLULA: CS(NB),CI(NB),CB(NB),CAUX(NB)
	!VAZÃO ESPECIFICA DE BASE (M3/S/KM2): QESP(NB)

	WM=0.0
	B=0.0
	KINS=0.0
	KBAS=0.0
	PLAM=0.0
	AUX=0.0
	CS=0.0
	CAUX=0.0
	CB=0.0
	CI=0.0

	OPEN(FILUSO,FILE='.\input\PARUSO.HIG',STATUS='OLD')

	DO KB=1,NB	    
		READ(FILUSO,72)CABE(1)
		READ(FILUSO,72)(CABE(K),K=1,5)
!@ DCB set/2012 write(*,*) kb
		DO IU=1,NU
!@ DCB set/2012		write(*,*) iu
			READ(FILUSO,71)AUSO(IU),WM(KB,IU),B(KB,IU),KBAS(KB,IU),KINS(KB,IU),PLAM(KB,IU),CAP(KB,IU),WC(KB,IU)           
            !READ(FILUSO,*)AUSO(IU),WM(KB,IU),B(KB,IU),KBAS(KB,IU),KINS(KB,IU),PLAM(KB,IU),CAP(KB,IU),WC(KB,IU) 
!			write(*,*) AUSO(IU),WM(KB,IU),B(KB,IU),KBAS(KB,IU),KINS(KB,IU),PLAM(KB,IU),CAP(KB,IU),WC(KB,IU) 
!			write(*,*)
			
		ENDDO

		READ(FILUSO,73)CABE(1),CS(KB)
		READ(FILUSO,73)CABE(2),CI(KB)
		READ(FILUSO,73)CABE(3),CB(KB)
		READ(FILUSO,74)CABE(4),QESP(KB)

!		write(*,*) CS(KB),CI(KB),CB(KB),QESP(KB)


	ENDDO

		
	CLOSE (FILUSO)

71	FORMAT(A10,7F8.3)
72	FORMAT(7A10)
73	FORMAT(A10,F8.1)
74	FORMAT(A10,F8.6)


	RETURN
	END