	SUBROUTINE LEVAR
	!esta subrotina le o arquivo em que estao os dados
	!de albedo e IAF, variaveis mensalmente,
	!para cada uso
	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER K !,IU
	character (10) CABEV
	CHARACTER (5) AMES(12)
	OPEN(FILVAR,FILE='.\input\ALBIAF.HIG',STATUS='OLD')
	!LE ALBEDDO
	READ(FILVAR,71)cabev
	READ(FILVAR,73)cabev,(AMES(K),K=1,12)
	DO IU=1,NU
		READ(FILVAR,72)AUSO(IU),(ALB(IU,K),K=1,12)
	ENDDO
	!LE IAF
	READ(FILVAR,71)cabev
	READ(FILVAR,73)cabev,(AMES(K),K=1,12)
	DO IU=1,NU
		READ(FILVAR,72)AUSO(IU),(RIAF(IU,K),K=1,12)
	ENDDO
	!LE Z (ALTURA MÉDIA DA VEGETAÇÃO)
	READ(FILVAR,71)cabev
	READ(FILVAR,73)cabev,(AMES(K),K=1,12)
	DO IU=1,NU
		READ(FILVAR,72)AUSO(IU),(Z(IU,K),K=1,12)
	ENDDO
	!LE RS (RESISTÊNCIA SUPERFICIAL DA VEGETAÇÃO)
	READ(FILVAR,71)cabev
	READ(FILVAR,73)cabev,(AMES(K),K=1,12)
	DO IU=1,NU
		READ(FILVAR,72)AUSO(IU),(RS(IU,K),K=1,12)
	ENDDO
	CLOSE(FILVAR)
71	FORMAT(A10)
72	FORMAT(A10,12F5.2)
73	FORMAT(A10,12A5)
	RETURN
	END