	SUBROUTINE PARCUNGE
	!Esta rotina calcula o valor ideal de
	!1- dtcal (intervalo de tempo de calculo da propagação)
	!2- ntrech (numero de subtrechos em que sera dividida a propagação)
	USE VARS_MAIN
	use aux_mod !RP
	IMPLICIT NONE
	INTEGER KH !CONTADOR
	INTEGER IWCT,NTRECH
	REAL RUGPLAN 	!RUGOSIDADE !FMF em 06/05/2019 - leitura do novo MINI.GTP
	REAL DQ,DA,CELTEMP,HMUP,BTOT,AMENOR,BINUN,PERIM,QPLAN,APLAN,RPLAN,QMENOR !VARIAVEL AUXILIAR
	REAL COEF,AT,DTCAL 	!VARIAVEIS AUXILIARES
	REAL DX,DX1,DX2,XACC,RTSAFE		!VARIAVEIS PARA NEWTON-RAPHSON	
	REAL DECLIV,ALONG,CLX 	!VARIAVEIS AUXILIARES

	!FMF em 06/05/2019 - leitura do novo MINI.GTP
	!RUGMAN=0.030 !COEFICIENTE DE MANNING É CONSIDERADO FIXO EM 0,03 PARA TODOS OS TRECHOS E RIOS

	ICODMUSK=0 !POR PRINCIPIO CONSIDERA TODAS AS PROPAGACOES POR MUSKINGUN CUNGE LINEAR
!@ DCB ago/2012	open(1111111,file='.\output\dxcalcMusk.txt')
!@ DCB ago/2012	write(1111111,*) 'IC    Crit1    Fread'
	DO IC=1,NC !LOOP DAS CÉLULAS
!		if (hdFLAG(iC)==1) cycle !RP

!		WRITE(*,*)IC,ACEL(IC),ACUR(IC),SRIO(IC),DECL(IC)

		IF(OD(IC)>1)THEN ! Novo critério. Ordem das bacias
!		IF(ACEL(IC)>1.1.AND.ACUR(IC)/ACEL(IC)>1.5)THEN !AREAS FONTE, SEM RIO, NAO INTERESSAM
			COEF=1.67*DECL(IC)**0.3/RUGMAN(IC)**0.6 !FMF em 06/05/2019 - leitura do novo MINI.GTP
			CEL(IC)=COEF*(QREF(IC)/BRIO(IC))**0.4
			AT=DTP				
			DTCAL=AT/24. !PRIMERIA TENTATIVA
			IWCT=24
			!ESTIMATIVA INICIAL DE DX
			DX=(2.5*QREF(IC))/(BRIO(IC)*DECL(IC)*CEL(IC)) 
!			DX1=DX/5. !CERCA RAIZ POR BAIXO
!			DX2=50000.*DX !CERCA RAIZ POR CIMA
			DX1=DX/10. !CERCA RAIZ POR BAIXO
			DX2=5000000.*DX !CERCA RAIZ POR CIMA

			XACC=0.5 !ERRO ADMITIDO NA RAIZ (MEIO METRO)
			QRX=QREF(IC)
			DECLIV=DECL(IC)
			BRX=BRIO(IC)
			CLX=CEL(IC)
!			CLX=CLX/3.0 ! RP teste tirar depois
			
			!WC - mudança dia 20/03/2004 São Francisco: usa sempre dt = 1hora para muskingun


!			write(*,*) 'DX inicial', DX

			DX=0.5*CLX*DTCAL*(1+(1+1.5*(QRX/BRX)/(CLX**2*DECLIV*DTCAL))**0.5)! Criterio Fread(1992) Flow Routing, in Handbook of Hydrology, Maidment
!			write(*,*) 'DX final Fread', DX			

!			CALL NEWTRAP(RTSAFE,DX1,DX2,xacc,QRX,BRX,DECLIV,CLX,DTCAL) ! Critério Livro Tucci
!			DX=RTSAFE

!			write(*,*) 'DX final', DX
!@ DCB ago/2012			write(1111111,*) IC,DX,0.5*CLX*DTCAL*(1+(1+1.5*(QRX/BRX)/(CLX**2*DECLIV*DTCAL))**0.5)
		
				!TESTA ESTE DX
			ALONG=SRIO(IC)*1000. !CONVERTE PARA METROS 
			NTRECH=NINT(ALONG/DX) !CALCULA NUMERO DE TRECHOS
			NTRECH=MAX(NTRECH,1)
			IF(NTRECH.GT.NUMUSK)THEN 
                write(*,*),IC
				WRITE(*,*) 'NUMERO DE SUB-TRECHOS MAIOR QUE', NUMUSK,' NA ROTINA PARCUNGE!!!'
				STOP 'PAROU '
			ENDIF
			DT(IC)=DTCAL
			NSUBT(IC)=NTRECH
			!WRITE(*,*)IC,DT(IC),NTRECH,ALONG,DX,CEL(IC)*DT(IC)/(ALONG/NTRECH)
			!WRITE(*,*)'CELERIDADE=',CEL(IC)
			

		ELSE
			DT(IC)=0.0
			NSUBT(IC)=0
		
!@ DCB ago/2012			write(1111111,*) IC,0.0,0.0
		ENDIF

	ENDDO !FIM DO LOOP DAS CÉLULAS
	
	RETURN
	END