	SUBROUTINE PARCEL

	!CALCULA ALGUNS PARÂMETROS DA CÉLULA E DO RIO

	USE VARS_MAIN
	IMPLICIT NONE
	INTEGER IW


	!CALCULA TEMPO DE CONCENTRACAO NA CELULA
	DO IW=1,NC

		!XLADO=ACEL(IW)**0.5 !ESTIMATIVA DO COMPRIMENTO
		XLADO=LCEL(IW) !COMPRIMENTO DO AFLUENTE PRINCIPAL DENTRO DA SUB-BACIA EM KM !RP
		!DH=HCEL(IW)-LCEL(IW)
		DH=HCEL(IW)*LCEL(IW) !VARIAÇÃO DE ALTITUDE AO LONGO DO CURSO DO AFLUENTE PRINCIPAL (EM m) !RP

		TIND(IW)=3600.*((0.868*XLADO**3.0)/DH)**0.385	!TEMPO DE CONCENTRAÇÃO POR KIRPICH EM SEGUNDOS
	ENDDO

	CALL INTECLIM 	!INTERPOLA VALORES DAS VARIAVEIS CLIMATOLOGICAS

   !FMF em 06/05/2019 - leitura do novo MINI.GTP
!!!	!CALCULA LARGURA DO RIO E VAZAO DE REFERENCIA
!!!	DO IC=1,NC
!!!		IF(ACUR(IC).GT.1.0)THEN	 !AREAS FONTE, SEM RIO, NAO INTERESSAM
!!!			ARX=ACUR(IC)  !AREA DRENADA - VARIÁVEL AUXILIAR
!!!			CALL REGION
!!!			BRIO(IC)=BRX	 !LARGURA DO RIO
!!!			HRIO(IC)=HRX  !PROFUNDIDADE DO RIO
!!!			QREF(IC)=QRX !VAZAO DE REFERENCIA
!!!		ELSE
!!!		BRIO(IC)=0.0
!!!		QREF(IC)=0.0
!!!		ENDIF
!!!	ENDDO

	!FIM DO CALCULO DA LARGURA E VAZAO DE REFERENCIA
	RETURN
	END
