	SUBROUTINE PREVISAO
	!Esta subrotina comanda o loop do tempo do modelo hidrológico e chama as 
	!rotinas de balanco e propagação nas células e de propagação na rede de drenagem
	USE VARS_MAIN
	USE AUX_MOD
	USE TIME_MOD
	IMPLICIT NONE

	INTEGER K,KHID !CONTADORES
	INTEGER KB,JCB,MWP 	!CONTADORES
	INTEGER IANTE,ITP,IHORIZ,INIPREV,IFIPREV,LINIARQ
	CHARACTER (15) ARQPREV !NOME DO ARQUIVO DE CHUVA PREVISTA MODELO GLOBAL CPTEC
	!CHARACTER (17) ARQPREV !NOME DO ARQUIVO DE CHUVA PREVISTA MODELO ETA
	INTEGER ITEMP
	REAL ERROANT1,ERROANT2,ERROCORR
	REAL RIANTE,RIHORIZ
	INTEGER IOPCHU
	CHARACTER (4) ABOBO
	INTEGER IDIAPREV,IANOPREV,IMESPREV,IP

	REAL QPMENS(29)
	INTEGER MDIAS,CONTADOR
	INTEGER ITINI,IBOBO
	CHARACTER (1) BARRA
	INTEGER NTRECH,NTMUSK,LT,I,J
	INTEGER IANTEMES,LDIA(NT),LMES(NT),LANO(NT)



	allocate(POSTORIO(nb),POSTOBAS(nb),POSTOINT(nb),POSTOSUP(nb))
	ALLOCATE (QRG0(NUMHIDG,NT)) !HIDROGRAMAS PARA GRAVAÇÃO
	QRG0=0.0

	OPEN(FILHID,FILE='.\output\VAZAO.HIG',STATUS='UNKNOWN')
	OPEN(55552,FILE='.\output\VAZAO0.HIG',STATUS='UNKNOWN')
	OPEN(5551,FILE='.\input\ParPrev.hig',STATUS='UNKNOWN')
	read(5551,*)
	do i=1,nB
		read(5551,*) J,POSTORIO(i),POSTOBAS(i),POSTOINT(i),POSTOSUP(i)
	enddo

	!OPEN(555,FILE='ETA40_M5.txt',STATUS='OLD',ACTION='READ') !LE LISTA DE ARQUIVOS DO MODELO GLOBAL
	!OPEN(555,FILE='GLOBAL_M1.txt',STATUS='OLD',ACTION='READ') !LE LISTA DE ARQUIVOS DO MODELO GLOBAL

	OPEN(555,FILE='.\input\ListaPREV.txt',STATUS='OLD',ACTION='READ') !LE LISTA DE ARQUIVOS DO MODELO GLOBAL


	!OPEN(555,FILE='ETA INTERPOLADOS.TXT',STATUS='OLD',ACTION='READ') !LE LISTA DE ARQUIVOS DO ETA CURTO PRAZO
	READ(555,*)ABOBO

	ITINI=1
	IHORIZ=60 ! Horizonte de previzao:
	IFIPREV=NT-IHORIZ !INTERVALO DE TEMPO EM QUE DEVE parar de fazer previsão


	OPEN(31,FILE='.\output\PREVISAO CURTA.TXT',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM HIDROGRAMAS CALCULADOS
	OPEN(32,FILE='.\output\PREVISAO MENSAL.TXT',STATUS='UNKNOWN') !ARQUIVO DE SAIDA COM HIDROGRAMAS MENSAIS PREVISTOS




	!	INICIO DO LOOP DO TEMPO

	IT=ITINI-1
	
	DO WHILE (IT<NT-100)
		IT=IT+1
		WRITE(*,72)IT,100*IT/NT
		!WRITE(*,*)ERROSOBRA
		72 FORMAT('+',' INTERVALO DE TEMPO:',I10,I10,'%')

		IF(IT==ITINI)THEN !PRIMEIRO INTERVALO DE TEMPO, CONDIÇÕES INICIAIS ESTIMADAS

			!**********CONDIÇÕES INICIAIS*********************************************
			call CondInic
		
			!DAS VAZÕES PREVISTAS
			QPREV=-1.0 !CÓDIGO DE FALTA DE PREVISÃO

			!*************FIM DAS CONDIÇÕES INICIAIS*********************************

		ELSE !OUTROS INTERVALOS DE TEMPO, CONDIÇÕES INICIAIS DADAS PELOS VALORES GUARDADOS
			!DO SOLO
			W=WPREV
			!DOS RESERVATORIOS SUBTERRANEO, SUBSUPERFICIAL E SUPERFICIAL e vazao nos rios Muskingum Cunge
			VBAS=VBASPREV
			VINT=VINTPREV
			VSUP=VSUPPREV
			TA=TAPREV
			QM2=QM2PREV
			QJ2=QJ2PREV
			SI=SIPREV
			QJ1=QJ1PREV
			QRIOINI=QRIOINIPREV
			QCONTORM=QCONTORMPREV
			QCONTORJ=QCONTORJPREV
			QCEL1=QCEL1PREV
			QCEL2=QCEL2PREV
			PMB2=PMB2PREV
			PMI2=PMI2PREV
			PMS2=PMS2PREV
			PJB2=PJB2PREV
			PJI2=PJI2PREV
			PJS2=PJS2PREV

			! Incluir variaveis de estado do modelo hidrodinamico !RP
			! Interceptação
			QO=QOprev
			HO=HOprev
			Qmin=Qminprev
			HminFLAG=HminFLAGprev

		ENDIF

		JDIA=IDINI+IT-1 !VERIFICA QUAL É O DIA DO CALENDÁRIO 
		CALL CALDAT(JDIA,IMES,IDIA,IANO)

		LANO(IT)=IANO
		LMES(IT)=IMES
		LDIA(IT)=IDIA

		!SUBROTINA DE LEITURA E PREPARACAO DA CHUVA
		ITCHUVA=IT
		CALL LECHUVA

		!SUBROTINA DE PREPARAÇÃO DOS DADOS CLIMATOL.
		TONTEM=TA
		CALL LECLIMA
	
		!SUBROTINA DA CELULA
		CALL CELULA
	
		!SUBROTINA DA REDE DE DRENAGEM
		CALL REDE
		
		! Modelo hidrodinâmico:
		IF (hdFLAG0>0) CALL Hidrodinamico2



		!ARMAZENA DADOS DE VAZÃO DAS CÉLULAS EM QUE EXISTE VAZÃO OBSERVADA
		DO K=1,NOBS
			KHID=IQOBS(K) !CÉLULA QUE CORRESPONDE AO POSTO
			QR(K,IT)=QJ2(KHID) !QR(K,IT) VAI SER COMPARADO A QOBS(K,IT) NA ROTINA FOBJ
		ENDDO
	
		DO KB=1,NB	!ARMAZENA VAZOES DAS SUB-BACIAS
			JCB=IEXUT(KB) !CELULA DO EXUTORIO DA SUB-BACIA KB
			QRB(KB,IT)=QJ2(JCB)
		ENDDO
	
		DO K=1,NUMHIDG !GUARDA DADOS PARA GRAVAR HIDROGRAMAS EM LOCAIS DEFINIDOS NO ARQUIVO PARHIG 
			KHID=IHIDG(K) !IHIDG(K) É O NÚMERO DA CÉLULA EM QUE SE DESEJA O HIDROGRAMA
			QRG(K,IT)=QJ2(KHID) !QRG ARAMZENA OS HIDROGRAMAS NOS LOCAIS DESEJADOS
		ENDDO
	

	
		!GUARDA VALORES DAS VARIÁVEIS MAIS IMPORTANTES ANTES DE COMEÇAR O CICLO DE PREVISÃO
		WPREV=W
		VBASPREV=VBAS
		VINTPREV=VINT
		VSUPPREV=VSUP
		TAPREV=TA
		QM2PREV=QM2
		QJ2PREV=QJ2
		SIPREV=SI
		QJ1PREV=QJ1
		QRIOINIPREV=QRIOINI
		QCONTORMPREV=QCONTORM
		QCONTORJPREV=QCONTORJ
		QCEL1PREV=QCEL1
		QCEL2PREV=QCEL2
		PMB2PREV=PMB2
		PMI2PREV=PMI2
		PMS2PREV=PMS2
		PJB2PREV=PJB2
		PJI2PREV=PJI2
		PJS2PREV=PJS2

		! Incluir variaveis de estado do modelo hidrodinamico !RP
		! Interceptação
		QOprev=QO
		HOprev=HO
		Qminprev=Qmin
		HminFLAGprev=HminFLAG



		!CICLO DE PREVISÃO - UTILIZA CHUVA QUE PODE ESTAR ERRADA
		
		if(it>itini+30)then
			CALL ATUALIZA !CHAMA A SUBROTINA DE ATUALIZAÇÃO 
		endif

		! Guarda hidrogramas em lag0:
		DO K=1,NUMHIDG !GUARDA DADOS PARA GRAVAR HIDROGRAMAS EM LOCAIS DEFINIDOS NO ARQUIVO PARHIG 
			KHID=IHIDG(K) !IHIDG(K) É O NÚMERO DA CÉLULA EM QUE SE DESEJA O HIDROGRAMA
			QRG0(K,IT)=QJ2(KHID) !QRG ARAMZENA OS HIDROGRAMAS NOS LOCAIS DESEJADOS
		ENDDO

		ITEMP=IT

		JDIA=IDINI+ITEMP+1 !VERIFICA QUAL É O DIA DO CALENDÁRIO EM QUE ESTÁ INICIANDO A PREVISAO
		CALL CALDAT(JDIA,IMES,IDIA,IANO) !VERIFICA DATA CORRESPONDENTE
		
		READ(555,79,END=19)ARQPREV,ABOBO,IDIAPREV,IMESPREV,IANOPREV,IHORIZ

		!79 FORMAT(A17,A1,2I2,I4,I5)
		79 FORMAT(A15,A4,2I2,I4,I5)

		!READ(555,79)IBOBO,ABOBO,ARQPREV,ABOBO,IDIAPREV,BARRA,IMESPREV,BARRA,IANOPREV

		!79 FORMAT(I10,A1,A11,A1,I2,A1,I2,A1,I4)


		IF(IDIA==IDIAPREV.AND.IMES==IMESPREV.AND.IANO==IANOPREV)THEN 
			WRITE(*,*)' INICIANDO PREVISÃO COM ARQUIVO',ARQPREV
			INIPREV=IT !PERMITE QUE FAÇA A PREVISÃO
		ELSE
			BACKSPACE (555)
			INIPREV=IT+2 !EVITA QUE FAÇA PREVISÃO
		ENDIF

		DO ITP=IT+1,IT+IHORIZ !CALCULA ALGUNS INTERVALOS DE TEMPO PARA PREVISÃO

			JDIA=IDINI+ITEMP+1 !VERIFICA QUAL É O DIA DO CALENDÁRIO EM QUE ESTÁ INICIANDO A PREVISAO
			CALL CALDAT(JDIA,IMES,IDIA,IANO) !VERIFICA DATA CORRESPONDENTE
			LANO(ITP)=IANO
			LMES(ITP)=IMES
			LDIA(ITP)=IDIA

			IF(ITP<=INIPREV)EXIT !SAI DA PREVISÃO QUANDO NÃO DEVE FAZER

			!verifica qual chuva deve ser utilizada
			IF(IDIA==IDIAPREV.AND.IMES==IMESPREV.AND.IANO==IANOPREV)THEN !USA CHUVA PREVISTA
				IOPCHU=2 !USA CHUVA PREVISTA
				OPEN(FILPREV,FILE='.\input\'//ARQPREV,STATUS='old',RECL=NC,FORM='UNFORMATTED',ACCESS='DIRECT') !dados PREVISÃO de chuva interpolados
				!OPEN(FILPREV,FILE=ARQPREV//'.ETA',STATUS='old',RECL=NC,FORM='UNFORMATTED',ACCESS='DIRECT') !dados PREVISÃO de chuva interpolados
			ELSE
				IOPCHU=1 !USA CHUVA OBSERVADA
			ENDIF

			IOPCHU=1 !USA SEMPRE CHUVA OBSERVADA

			!SUBROTINA DE LEITURA E PREPARACAO DA CHUVA
			ITCHUVA=ITP
			JDIA=IDINI+ITP !VERIFICA QUAL É O DIA DO CALENDÁRIO 
			CALL CALDAT(JDIA,IMES,IDIA,IANO)

			IANTE=ITP-ITEMP !IANTE É A ANTECEDêNCIA DA PREVISÃO QUE ESTÁ SENDO GRAVADA 
			
			IF(IT>=INIPREV.AND.IT<IFIPREV)THEN
				SELECT CASE (IOPCHU)
				CASE (1) !CHUVA OBSERVADA
					ITCHUVA=ITP
					CALL LECHUVA !USA CHUVA OBSERVADA
				CASE (2) !CHUVA PREVISTA
					ITCHUVA=ITP-ITEMP
					!IF(IANTE<=10)THEN
						CALL LEPREV
					!ELSE
					!	P=0.0
					!ENDIF
				CASE DEFAULT
					STOP 'OPCAO DE CHUVA DESCONHECIDA'
				ENDSELECT
				!P=0.0 !USA CHUVA IGUAL A ZERO
			ELSE
				EXIT !SÓ FAZ PREVISÃO PARA O PERÍODO DESEJADO
			ENDIF
			IT=ITP

			IF(IANTE==1)THEN
				WRITE(*,73)IDIA,IMES,IANO,IHORIZ
			ENDIF


			!write(*,*)itEMP,itp,ERROMORPA,ERROSOBRA
				
			!SUBROTINA DE PREPARAÇÃO DOS DADOS CLIMATOL.
			TONTEM=TA
			CALL LECLIMA
			!SUBROTINA DA CELULA
			CALL CELULA
			!SUBROTINA DA REDE DE DRENAGEM
			CALL REDE
			! Modelo hidrodinâmico:
			IF (hdFLAG0>0) CALL Hidrodinamico2
	


			!ARMAZENA DADOS DE VAZÃO DAS CÉLULAS EM QUE EXISTE VAZÃO OBSERVADA
			DO K=1,NOBS
				KHID=IQOBS(K) !CÉLULA QUE CORRESPONDE AO POSTO
				QR(K,IT)=QJ2(KHID) !QR(K,IT) VAI SER COMPARADO A QOBS(K,IT) NA ROTINA FOBJ
			ENDDO


			76 FORMAT('+',3I10,2F10.1)
			DO K=1,NUMHIDG !GUARDA DADOS PARA GRAVAR HIDROGRAMAS EM LOCAIS DEFINIDOS NO ARQUIVO PARHIG 
				KHID=IHIDG(K) !IHIDG(K) É O NÚMERO DA CÉLULA EM QUE SE DESEJA O HIDROGRAMA
				QPREV(K,IANTE,ITP)=QJ2(KHID) !QPREV ARMAZENA VAZÕES PREVISTAS NOS LOCAIS DESEJADOS
			ENDDO

			!GRAVA ARQUIVO DE HIDROGRAMA DE PREVISÃO T0 CONSTANTE
			IF(IANTE==1)THEN
				JDIA=IDINI+ITEMP
				CALL CALDAT(JDIA,IMES,IDIA,IANO)
				!grava informações no arquivo diário
				WRITE(31,73)IDIA,IMES,IANO,IHORIZ
				73 FORMAT(' PREVISAO INICIADA EM ',I2,'/',I2,'/',I4,'  HORIZONTE ',I6)
				!grava informações no arquivo mensal
				!WRITE(32,74)IDIA,IMES,IANO
				write(32,*)

				74 FORMAT(' PREVISAO INICIADA EM ',I2,'/',I2,'/',I4)
				QPMENS=0.0
				IANTEMES=0
			ENDIF

			JDIA=IDINI+ITP !VERIFICA QUAL É O DIA DO CALENDÁRIO 
			CALL CALDAT(JDIA,IMES,IDIA,IANO)

			WRITE(31,77)ITEMP,ITP,IANTE,IDIA,IMES,IANO,(QJ2(IHIDG(IP)),IP=1,NUMHIDG) !,QJ2(IHIDG(4)),QJ2(IHIDG(13)),QJ2(IHIDG(18)),QJ2(IHIDG(21))
			77 FORMAT(6I6,<NUMHIDG>F15.3)
		

			!SÓ GRAVA VAZOES MEDIAS MENSAIS NO FINAL DE CADA MES			
			IF(IMES==1.OR.IMES==3.OR.IMES==5.OR.IMES==7.OR.IMES==8.OR.IMES==10.OR.IMES==12)THEN
				MDIAS=31
			ELSEIF(IMES==2)THEN
				IF(MOD(IANO,4)==0)THEN
					MDIAS=29
				ELSE
					MDIAS=28
				ENDIF
			ELSE
				MDIAS=30
			ENDIF
			DO IP=1,29
				QPMENS(IP)=QPMENS(IP)+QJ2(IHIDG(IP))
			ENDDO

			IF(IDIA==MDIAS)THEN
				IANTEMES=IANTEMES+1
				DO IP=1,29
					QPMENS(IP)=QPMENS(IP)/MDIAS !CALCULA MÉDIA MENSAL
				ENDDO
				WRITE(32,78)IMES,IANO,(QPMENS(IP),IP=1,NUMHIDG) !GRAVA VAZÕES PREVISTAS MEDIAS MENSAIS


				78 FORMAT(I4,'/',I4,' ',<NUMHIDG>F15.3)
				QPMENS=0.0
			ENDIF

		ENDDO !FIM DO LOOP DA PREVISÃO

		IT=ITEMP



		CLOSE (FILPREV)

	ENDDO !FIM DO LOOP DO TEMPO

19	CONTINUE
	


	DO IT=1,NT
		!GRAVA HIDROGRAMAS NOS NB EXUTORIOS DESEJADOS 
		WRITE(FILHID,71)IT,(QRG(KB,IT),KB=1,NUMHIDG)
		WRITE(55552,71)IT,(QRG0(KB,IT),KB=1,NUMHIDG)
	ENDDO
	CLOSE (FILHID)

71	FORMAT(I10,<NUMHIDG>F15.3)
75	FORMAT(I6,24F7.0)
     
	RETURN
	END

