	
	SUBROUTINE REGION

	!ESTA SUBROTINA CALCULA 
	!1 -	A LARGURA DO RIO COM BASE EM UMA FUNÇÃO
	!		QUE RELACIONA A LARGURA À ÁREA DE DRENAGEM
	!		FORNECIDA PELO USUARIO
	!2 -	UMA VAZAO DE REFERENCIA
	USE VARS_MAIN
	IMPLICIT NONE

	REAL QMESP !VAZAO MEDIA ESPECIFICA EM L/S/KM2

!	QMESP=17. !VALOR RAZOÁVEL EM L/S/KM2 VÁLIDO PARA RIO TAQUARI ANTAS
	
	QMESP=30. !VALOR RAZOÁVEL EM L/S/KM2 VÁLIDO PARA BACIA AMAZONICA

	QRX=QMESP*ARX/1000.  !VAZAO DE REFERENCIA

	!____LARGURA X AREA DA BACIA DADOS VÁLIDOS PARA RIO TAQUARI ANTAS
!	BRX=5.2466*ARX**0.4106


	!____LARGURA X AREA DA BACIA DADOS VÁLIDOS PARA BACIA AMAZÔNICA
	BRX=0.8054*ARX**0.5289

	RETURN
	END
