	MODULE VARS_CALIB
	!DECLARA VARIÁVEIS DO MÉTODO DE CALIBRAÇÃO
	IMPLICIT NONE
	SAVE
	INTEGER ISEED
	INTEGER KOUNTF,ISHUFFLE,ISOMA,IDOMIN,IDD,NPC
	REAL FMIN,SPARET,RMAX,XRAND,PINI,DIFPAR
	INTEGER IREJECT,LRUIM
	REAL,ALLOCATABLE:: FO(:,:)
	INTEGER, ALLOCATABLE:: IPARET(:),IRUIM(:)
	REAL, ALLOCATABLE:: PPAR(:,:) 
	REAL, ALLOCATABLE:: PAR(:,:),PARX(:)
	REAL, ALLOCATABLE:: PMIN(:),PMAX(:)
	REAL, ALLOCATABLE:: FOLD(:)
	REAL, ALLOCATABLE:: MEDIA(:)
	REAL,ALLOCATABLE::XPAR(:)
	REAL,ALLOCATABLE:: SPAR(:,:,:),FPLEX(:,:,:)
	REAL,ALLOCATABLE:: SOMAPAR(:),REFLEX(:),CONTRA(:)
	REAL,ALLOCATABLE:: PROB(:)
	REAL,ALLOCATABLE:: VMIN(:) !VALOR MINIMO DAS FUNÇÕES OBJETIVO
	INTEGER:: NPAR !NUMERO DE PARAMETROS DA FUNÇÃO A OTIMIZAR
	INTEGER:: NS !NUMERO DE PONTOS DA AMOSTRA INICIAL
	INTEGER:: NF !NUMERO DE FUNÇÕES OBJETIVO A OTIMIZAR
	
	INTEGER,ALLOCATABLE:: p_Calib(:,:),iFO(:),IBCONGEL(:)
	INTEGER:: iMaxGen,NCONGEL
	!FIM DAS VARIÁVEIS DO MÉTODO DE CALIBRAÇÃO 
	END MODULE VARS_CALIB
