        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:36 2019
        MODULE ALLOCA_VARS__genmod
          INTERFACE 
            SUBROUTINE ALLOCA_VARS(IOP)
              INTEGER(KIND=4) :: IOP
            END SUBROUTINE ALLOCA_VARS
          END INTERFACE 
        END MODULE ALLOCA_VARS__genmod
