        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:15 2019
        MODULE ALLOCA_CALIB__genmod
          INTERFACE 
            SUBROUTINE ALLOCA_CALIB(IOP)
              INTEGER(KIND=4) :: IOP
            END SUBROUTINE ALLOCA_CALIB
          END INTERFACE 
        END MODULE ALLOCA_CALIB__genmod
