        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:19 2019
        MODULE ARQCLISUB__genmod
          INTERFACE 
            SUBROUTINE ARQCLISUB
            END SUBROUTINE ARQCLISUB
          END INTERFACE 
        END MODULE ARQCLISUB__genmod
