        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:21 2019
        MODULE CALIBRA__genmod
          INTERFACE 
            SUBROUTINE CALIBRA
            END SUBROUTINE CALIBRA
          END INTERFACE 
        END MODULE CALIBRA__genmod
