        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:34 2019
        MODULE CONDINIC__genmod
          INTERFACE 
            SUBROUTINE CONDINIC
            END SUBROUTINE CONDINIC
          END INTERFACE 
        END MODULE CONDINIC__genmod
