        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:36 2019
        MODULE HD_CONDINIC__genmod
          INTERFACE 
            SUBROUTINE HD_CONDINIC
            END SUBROUTINE HD_CONDINIC
          END INTERFACE 
        END MODULE HD_CONDINIC__genmod
