        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:21 2019
        MODULE INTECLIM__genmod
          INTERFACE 
            SUBROUTINE INTECLIM
            END SUBROUTINE INTECLIM
          END INTERFACE 
        END MODULE INTECLIM__genmod
