        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:25 2019
        MODULE INTERPMUSK__genmod
          INTERFACE 
            SUBROUTINE INTERPMUSK(QMUSKNL,CELMUSKNL,BMUSKNL)
              REAL(KIND=4) :: QMUSKNL
              REAL(KIND=4) :: CELMUSKNL
              REAL(KIND=4) :: BMUSKNL
            END SUBROUTINE INTERPMUSK
          END INTERFACE 
        END MODULE INTERPMUSK__genmod
