        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:37 2019
        MODULE LECALIB__genmod
          INTERFACE 
            SUBROUTINE LECALIB
            END SUBROUTINE LECALIB
          END INTERFACE 
        END MODULE LECALIB__genmod
