        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:30 2019
        MODULE LECELL__genmod
          INTERFACE 
            SUBROUTINE LECELL
              USE VARS_MAIN
            END SUBROUTINE LECELL
          END INTERFACE 
        END MODULE LECELL__genmod
