        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:19 2019
        MODULE LECHUVA__genmod
          INTERFACE 
            SUBROUTINE LECHUVA
            END SUBROUTINE LECHUVA
          END INTERFACE 
        END MODULE LECHUVA__genmod
