        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:29 2019
        MODULE LECLIMED__genmod
          INTERFACE 
            SUBROUTINE LECLIMED
            END SUBROUTINE LECLIMED
          END INTERFACE 
        END MODULE LECLIMED__genmod
