        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:39 2019
        MODULE LECLIMA__genmod
          INTERFACE 
            SUBROUTINE LECLIMA
            END SUBROUTINE LECLIMA
          END INTERFACE 
        END MODULE LECLIMA__genmod
