        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:33 2019
        MODULE LEFIX__genmod
          INTERFACE 
            SUBROUTINE LEFIX
            END SUBROUTINE LEFIX
          END INTERFACE 
        END MODULE LEFIX__genmod
