        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:31 2019
        MODULE LEOUTROSQ__genmod
          INTERFACE 
            SUBROUTINE LEOUTROSQ
            END SUBROUTINE LEOUTROSQ
          END INTERFACE 
        END MODULE LEOUTROSQ__genmod
