        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:35 2019
        MODULE LEPREV__genmod
          INTERFACE 
            SUBROUTINE LEPREV
            END SUBROUTINE LEPREV
          END INTERFACE 
        END MODULE LEPREV__genmod
