        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:41 2019
        MODULE LESUBST__genmod
          INTERFACE 
            SUBROUTINE LESUBST
            END SUBROUTINE LESUBST
          END INTERFACE 
        END MODULE LESUBST__genmod
