        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:20 2019
        MODULE LEVAR__genmod
          INTERFACE 
            SUBROUTINE LEVAR
            END SUBROUTINE LEVAR
          END INTERFACE 
        END MODULE LEVAR__genmod
