        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:30 2019
        MODULE MATRIX2__genmod
          INTERFACE 
            SUBROUTINE MATRIX2
            END SUBROUTINE MATRIX2
          END INTERFACE 
        END MODULE MATRIX2__genmod
