        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:03 2019
        MODULE MATRIX__genmod
          INTERFACE 
            SUBROUTINE MATRIX
            END SUBROUTINE MATRIX
          END INTERFACE 
        END MODULE MATRIX__genmod
