        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:40 2019
        MODULE PARCUNGE__genmod
          INTERFACE 
            SUBROUTINE PARCUNGE
            END SUBROUTINE PARCUNGE
          END INTERFACE 
        END MODULE PARCUNGE__genmod
