        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:35 2019
        MODULE RADIACAO__genmod
          INTERFACE 
            SUBROUTINE RADIACAO
            END SUBROUTINE RADIACAO
          END INTERFACE 
        END MODULE RADIACAO__genmod
