        !COMPILER-GENERATED INTERFACE MODULE: Mon May 06 18:55:30 2019
        MODULE SED_INICIAL__genmod
          INTERFACE 
            SUBROUTINE SED_INICIAL
              USE VARS_MAIN
            END SUBROUTINE SED_INICIAL
          END INTERFACE 
        END MODULE SED_INICIAL__genmod
