        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:16 2019
        MODULE SEMENTE__genmod
          INTERFACE 
            SUBROUTINE SEMENTE(ISEED)
              INTEGER(KIND=4) :: ISEED
            END SUBROUTINE SEMENTE
          END INTERFACE 
        END MODULE SEMENTE__genmod
