        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:09:57 2019
        MODULE SKYLIN__genmod
          INTERFACE 
            SUBROUTINE SKYLIN
            END SUBROUTINE SKYLIN
          END INTERFACE 
        END MODULE SKYLIN__genmod
