        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:15 2019
        MODULE SKYLINE0__genmod
          INTERFACE 
            SUBROUTINE SKYLINE0
            END SUBROUTINE SKYLINE0
          END INTERFACE 
        END MODULE SKYLINE0__genmod
