        !COMPILER-GENERATED INTERFACE MODULE: Tue Apr 30 12:10:05 2019
        MODULE SKYOTM__genmod
          INTERFACE 
            SUBROUTINE SKYOTM
            END SUBROUTINE SKYOTM
          END INTERFACE 
        END MODULE SKYOTM__genmod
