	SUBROUTINE PROJECT_COMP(X1,X2,Y1,Y2,LX,LY,LXY,DX,DY,lado2,diag2)

	PARAMETER (PI=3.141592)
	REAL(KIND=8) X1,X2,Y1,Y2
	REAL(KIND=8) DX,DY
	REAL(KIND=8) LX,LY,LXY
	real(KIND=8) lado2,diag2

C	CALCULA DISTANCIAS SOBRE A SUPERFICIE CONSIDERANDO O ELIPSOIDE wgs84
C	AS EUQAÇÕES UTILIZADAS AQUI FORAM OBTIDAS EM UMA HOMEPAGE DE PETER DANA
C	DA UNIVERSIDADE DO COLORADO 
	A=6378.137 !COMPRIMENTO DO SEMI EIXO MAIOR DO ELIPSÓIDE (KM)
	B=6356.752 !COMPRIMENTO DO SEMI EIXO MENOR DO ELIPSÓIDE (KM)


	YLAT=(Y1+Y2)/2.

	F=(A-B)/A !ACHATAMENTO DO ELIPSÓIDE
	E2=2.*F-F**2. !QUADRADO DA EXCENTRICIDADE
	RN=A/(1.-E2*(SIND(YLAT)**2.))**0.5 !RAIO DE CURVATURA DA TERRA NA LATITUDE

	!CALCULA RAIO DA CIRCUNFERENCIA DE UM CIRCULO DETERMINADO PELO PLANO 
	!QUE CORTA O ELIPSÓIDE NA LATITUDE YLAT
	RCIRC=RN*COSD(YLAT)
	!

	DGX=X2-X1
	DGY=Y1-Y2


	DX=RCIRC*DGX*(PI/180.0)
	DY=RN*DGY*(PI/180.0)

      LX=DX*lado2
      LY=DY*lado2
      LXY=sqrt(DX**2+DY**2)*diag2/sqrt(2.)
       


	RETURN
	END